modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="All rights reserved" #mandatory
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="cagedmobs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Caged Mobs" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile="cagedmobs.png" #optional
#credits="Thanks!" #optional
authors="Corgam" #optional
#Description #mandatory
description='''
'''
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
